api_key_wb1 = 'eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjQwNTA2djEiLCJ0eXAiOiJKV1QifQ.eyJlbnQiOjEsImV4cCI6MTczMzk0OTczNywiaWQiOiJlZjYwNjUwNi0yYTBkLTRhOTYtYjNlNy00NmVmNjQwMTgxMjciLCJpaWQiOjQyOTQ4MDEyLCJvaWQiOjgxNzc5NiwicyI6OCwic2lkIjoiYmJmNDJhMzEtMTEwZS00YWRhLThiYmYtMDMyN2UwZmNhOWQ2IiwidCI6ZmFsc2UsInVpZCI6NDI5NDgwMTJ9.mEW6lIkboHTBh4vPEcTtxoB6Js35hLWwnt-pA3rzp2T2l10ZJv0FXRjLJ35sLk_28S627ZRgCA9CO0st0LLZxw'
api_key_wb2 = 'eyJhbGciOiJFUzI1NiIsImtpZCI6IjIwMjQwNjE3djEiLCJ0eXAiOiJKV1QifQ.eyJlbnQiOjEsImV4cCI6MTczNDYyNjM1NywiaWQiOiI3ZmFlOGVhMC1hNmMzLTRlMGUtYWZlOC1hNWE1MWNlOGU4NzAiLCJpaWQiOjMwNzE3OTQsIm9pZCI6OTE4MjUzLCJzIjo4LCJzaWQiOiI1Y2VjMWI3Ny0yNDgwLTQzZWQtYmRiNC1iMTc0MzRkNGFmNTQiLCJ0IjpmYWxzZSwidWlkIjozMDcxNzk0fQ.Y23YvDc2Ke3J9XfLFADwqe_ovlRN1ficTAlbEFixlKUwVKKyss2Rleq-q9etuMyJUgPGp-Kr4kzY5u7MckWWGQ'
articul_in_table = 0  # Столбец в котором записан артикул, отсчёт начинается с 0
price_in_table = 2  # Столбец в котором записана цена, отсчёт начинается с 0
spreadsheet_id = '1JfsDlQDFULyz7WOqGj6xFO9o_i1bmYAeNRz3z3zwlMo'  # id всей таблицы
start_time = "06:00"
table1_name = "MaxAnd"
table2_name = "Пчелка"
